from quantgrid.exceptions.internal_error import XLInternalError


class XLToolError(XLInternalError):
    pass
